### ISSUE TITLE
Некорректное хранение данных

### ISSUE THREAD

**Issue by sdam64** [twentytwo777/PP-System#1]
В случае аддона, для хранения информации о текущем режиме игрока используется файловая система сервера, что является абсолютным примером ОТВРАТИТЕЛЬНОЙ практики. Для хранения информации такого вида полагается использование нативных библиотек игры: а именно библиотеки SQLite (см. https://wiki.facepunch.com/gmod/sql)

Помимо всего прочего, сохранение режима игрока ПОСЛЕ его фактического выхода с сервера является нецелесообразным, по сему хранение этих данных необязательно и вовсе не требуется.

**Comment by twentytwo777** [comment]
ok
