### ISSUE TITLE
Незначительные исправления и оптимизация

### ISSUE THREAD

**Issue by Trek32** [twentytwo777/PP-System#3]
### Файл: server/pp.lua

1. В таймере отсутствует проверка валидности игрока, что может повлечь за собой вывод ошибки, в случае, если игрок выйдет до срабатывания таймера.

2. Многочисленные повторения функции Give, вместо того, чтобы сделать таблицу и перебрать её циклом, показав эту функцию в коде всего пару раз.

3. Передача нагруженного текстом пакета: **ChatPrint** отсылает пакет со строкой на клиент, каждый ANSI символ - 1 байт, UNICODE символ - 2 байта, соответственно, русские символы весят больше и данных передается в 2 раза больше и, т.к. пакет класса **UserMessage** имеет 2 поля типа **int** (хранящие в себе тип и размер в битах), можно передать максимум 248 байт. Это оказывает сетевую нагрузку как на сервер, так и на клиент. Для экономии трафика рекомендуется использование отдельного нетворка с последующей индексацией готовых пересылаемых сообщений. Индексы передавать функцией `net.WriteInt` с выбором минимального количества битов.

4. Использование сразу нескольких нетворков для выполнения похожих задач. Опять-таки, достаточно использовать один нетворк и передавать индексы, которые будут отвечать за определенные действия.

5. Использование таймеров, когда можно обойтись без них.

А также множество других недочетов.

**Comment by twentytwo777** [comment]
thx
